# CA1 Data Preparation Ciaran Lynch

## Add python libraries to analysis

In [55]:
import pandas as pd
import seaborn as sns
%matplotlib inline  
import matplotlib.pyplot as plt
import numpy as np

## Load the Dataset provided called student_dataV2

In [56]:
df = pd.read_csv("student_dataV2.csv")

### Characterisation of the data set

### Check  the data loaded correctly

In [57]:
df.head(5)

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   object
 1   Application mode                                4423 non-null   float64
 2   Application order                               4423 non-null   float64
 3   Course                                          4421 non-null   float64
 4   Daytime/evening attendance                      4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4420 non-null   float64
 7   Nacionality                                     4424 non-null   object
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4423 non-null   float64
 10  Mother's occupation                             4423 non-null   float64
 11  Father's occupation                             4423 non-null   object
 12  Admission grade                                 4422 non-null   float64
 13  Displaced                                       4424 non-null   object
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4423 non-null   float64
 16  Tuition fees up to date                         4423 non-null   object
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4423 non-null   object
 20  International                                   4423 non-null   float64
 21  Curricular units 1st sem (credited)             4424 non-null   object
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4423 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4423 non-null   float64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4423 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   float64
 34  Inflation rate                                  4424 non-null   float64
 35  GDP                                             4424 non-null   float64
 36  Target                                          4424 non-null   object
dtypes: float64(15), int64(14), object(8)
memory usage: 1.2+ MB

In [59]:
df.shape

(4424, 37)

#### We can see that the dataset contains 4424 rows of data and  37 columnss

### Rename the columns to make it more readable

In [60]:
df = df.rename(columns={
    "Marital status": "maritial_status",
    "Application mode": "application_mode",
    "Application order": "application_order",
    "Course": "course",
    "Daytime/evening attendance": "attendance_time",
    "Previous qualification": "previous_qual",
    "Previous qualification (grade)": "previous_grade",
    "Nacionality": "nationality",
    "Mother's qualification": "mothers_qual",
    "Father's qualification": "fathers_qual",
    "Mother's occupation.": "mothers_occupation",
    "Father's occupation": "fathers_occupation",
    "Admission grade": "admission_grade",
    "Educational special needs": "special_needs",
    "Debtor": "debtor",
    "Gender": "gender",
    "Age at enrollment": "enroll_age",
    "International": "international",
    "Curricular units 1st sem (credited)": "1st_sem_credit",
    "Curricular units 1st sem (enrolled)": "1st_sem_enrolled",
    "Curricular units 1st sem (evaluations)": "1st_sem_evaluation",
    "Curricular units 1st sem (approved)": "1st_sem_approved",
    "Curricular units 1st sem (grade)": "1st_sem_grade",
    "Curricular units 1st sem (without evaluations)": "1st_sem_without_eval",
    "Curricular units 2nd sem (credited) ": "2nd_sem_credit",
    "Curricular units 2nd sem (enrolled) ": "2nd_sem_enrolled",
    "Curricular units 2nd sem (evaluations)": "2nd_sem_evaluationn",
    "Curricular units 2nd sem (approved) ": "2nd_sem_approved",
    "Curricular units 2nd sem (grade)": "2nd_sem_grade",
    "Curricular units 2nd sem (without evaluations)": "1st_sem_without_eval",
    "Unemployment rate": "unemployed_rate",
    "Inflation rate": "inflation_rate"
    } 
    )

In [61]:
df.head(3)

,maritial_status,application_mode,application_order,course,attendance_time,previous_qual,previous_grade,nationality,mothers_qual,fathers_qual,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),2nd_sem_evaluationn,Curricular units 2nd sem (approved),2nd_sem_grade,1st_sem_without_eval,unemployed_rate,inflation_rate,GDP,Target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout

### Check for missing values in the dataset

In [62]:
df.isnull().sum()

maritial_status                        0
application_mode                       1
application_order                      1
course                                 3
attendance_time                        0
previous_qual                          0
previous_grade                         4
nationality                            0
mothers_qual                           0
fathers_qual                           1
Mother's occupation                    1
fathers_occupation                     1
admission_grade                        2
Displaced                              0
special_needs                          0
debtor                                 1
Tuition fees up to date                1
gender                                 0
Scholarship holder                     0
enroll_age                             1
international                          1
1st_sem_credit                         0
1st_sem_enrolled                       0
1st_sem_evaluation                     0
1st_sem_approved                       0
1st_sem_grade                          1
1st_sem_without_eval                   0
Curricular units 2nd sem (credited)    0
Curricular units 2nd sem (enrolled)    1
2nd_sem_evaluationn                    0
Curricular units 2nd sem (approved)    0
2nd_sem_grade                          1
1st_sem_without_eval                   0
unemployed_rate                        0
inflation_rate                         0
GDP                                    0
Target                                 0
dtype: int64

In [63]:
total_rows = len(df)
print("Total rows of data before dealing with missing rows: ", total_rows)

Total rows of data before dealing with missing rows:  4424

In [64]:
df = df.dropna()

In [65]:
new_rows = len(df)

In [66]:
print("rows of data after dropping missing values: " , new_rows)

rows of data after dropping missing values:  4405

In [67]:
total_dropped = total_rows -  new_rows
total_dropped

19

In [68]:
total_dropped / total_rows *100

0.4294755877034358

## Missing rows analysis
#### in total only 19 rows had missing data, this represented 0.42% of the overall dataset
### dropping the missing data, will have a negligible impact on the overall sample size

## Discriptive Statistics

In [29]:
df.describe()

,application_mode,application_order,course,attendance_time,previous_qual,previous_grade,mothers_qual,fathers_qual,Mother's occupation,admission_grade,...,1st_sem_without_eval,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),2nd_sem_evaluationn,Curricular units 2nd sem (approved),2nd_sem_grade,1st_sem_without_eval,unemployed_rate,inflation_rate,GDP
count,4423.000000,4423.000000,4421.000000,4424.000000,4424.000000,4420.000000,4424.000000,4423.000000,4423.000000,4422.000000,...,4424.000000,4424.000000,4423.000000,4424.000000,4424.000000,4423.000000,4424.000000,4424.000000,4424.000000,4424.000000
mean,18.663351,1.727560,8856.331147,0.890823,4.577758,132.621561,19.561935,22.271987,10.961338,126.988512,...,0.137658,0.541817,6.231743,8.063291,4.435805,10.229941,0.150316,11.566139,1.228029,0.001969
std,17.482509,1.313802,2064.221611,0.311897,10.216592,13.189209,15.603186,15.343244,26.421223,14.476775,...,0.690880,1.918546,2.196038,3.947951,3.014764,5.211367,0.753774,2.663850,1.382711,2.269935
min,1.000000,0.000000,33.000000,0.000000,1.000000,95.000000,1.000000,1.000000,0.000000,95.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000
25%,1.000000,1.000000,9085.000000,1.000000,1.000000,125.000000,2.000000,3.000000,4.000000,117.900000,...,0.000000,0.000000,5.000000,6.000000,2.000000,10.750000,0.000000,9.400000,0.300000,-1.700000
50%,17.000000,1.000000,9238.000000,1.000000,1.000000,133.100000,19.000000,19.000000,5.000000,126.100000,...,0.000000,0.000000,6.000000,8.000000,5.000000,12.200000,0.000000,11.100000,1.400000,0.320000
75%,39.000000,2.000000,9556.000000,1.000000,1.000000,140.000000,37.000000,37.000000,9.000000,134.800000,...,0.000000,0.000000,7.000000,10.000000,6.000000,13.333333,0.000000,13.900000,2.600000,1.790000
max,57.000000,9.000000,9991.000000,1.000000,43.000000,190.000000,44.000000,44.000000,194.000000,190.000000,...,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,16.200000,3.700000,3.510000